"""Shared helpers for turning a public dataset's raw layout into the internal contract.

Ported from ``../Thermal-To-Optical-Translation/src/t2o/data/adapters/common.py``, minus its
YOLO-label helpers: this project has no object classes until the Tier-2 box-transfer GT of
TASKS.md P2-10, and a label writer nothing reads is a maintenance liability.

**The contract keeps the sibling's ``visible``/``infrared`` segment names**, not this
project's ``optical``/``thermal`` vocabulary::

    <root>/<name>/{train,val}/{visible,infrared}/images/<stem><suffix>

Adapted datasets land next to ``processed/msrs`` and ``processed/flir`` in that same sibling
tree, and those two already use ``visible``/``infrared``. One directory holding two naming
conventions is how a pairing bug gets born, so the translation happens once, declaratively, in
the manifest's ``rgbt:`` block (``optical_token: visible``) -- exactly as the MSRS manifest
this project already reads has always done. ``data/pairing.py`` therefore needs no change.

Images are never re-encoded when their pixels are unchanged. :func:`place_image_pair`
hardlinks by default: a public dataset is read-only, DroneVehicle alone is 14 GB, and copying
would double it for no benefit. A hardlink -- unlike a symlink -- survives deletion of the raw
tree, which matters because ``raw/`` is the part a user is most likely to clear to reclaim
space. Cross-filesystem links fail, so the copy fallback stays.
"""

from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

DATA_FILENAME = "data.yaml"
IMAGES_SEGMENT = "images"
VISIBLE = "visible"
INFRARED = "infrared"
SPLITS = ("train", "val")


class AdapterError(ValueError):
    """Raised when a raw dataset's layout doesn't match what its adapter expects."""


def images_dir(split_root: Path, modality: str) -> Path:
    directory = split_root / modality / IMAGES_SEGMENT
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def place_image_pair(
    visible_src: Path, infrared_src: Path, stem: str, split_root: Path, suffix: str
) -> None:
    """Place one visible/infrared pair under ``split_root``, hardlinking where possible.

    Both destinations share ``stem`` and ``suffix``. That is required, not cosmetic:
    ``data/pairing.py`` derives the thermal counterpart by substituting *only* the modality
    path segment, so a filename that differs between the two sides is an unpairable file.
    """
    for modality, source in ((VISIBLE, visible_src), (INFRARED, infrared_src)):
        destination = images_dir(split_root, modality) / f"{stem}{suffix}"
        if destination.exists():
            continue
        try:
            os.link(source, destination)
        except OSError:
            # Different filesystem, or a filesystem without hardlinks. Correctness is
            # unaffected; only the disk saving is lost, so this is a debug note, not a warning.
            logger.debug("hardlink failed for %s; copying instead", destination)
            shutil.copyfile(source, destination)


def write_image_pair_bytes(
    visible_data: bytes, infrared_data: bytes, stem: str, split_root: Path, suffix: str
) -> None:
    """Byte-for-byte equivalent of :func:`place_image_pair` for a source that is not a file on
    disk -- an entry read straight out of a zip via ``ZipFile.read()``, which has no path
    ``os.link`` could take."""
    for modality, data in ((VISIBLE, visible_data), (INFRARED, infrared_data)):
        destination = images_dir(split_root, modality) / f"{stem}{suffix}"
        if not destination.exists():
            destination.write_bytes(data)


def write_pointer_manifest(destination: Path, adapted_root: Path) -> Path:
    """Write the ``data.yaml`` this repo reads, pointing at an adapted tree elsewhere.

    The bytes live in the sibling tree; this repo keeps only the pointer. ``dataset/`` is
    git-ignored wholesale here, so these manifests never reach the Windows training server --
    which is precisely why ``cmreg ingest`` generates them instead of assuming they are
    checked in. Same nine-line shape as the MSRS manifest that predates this module.
    """
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        "# Generated by `cmreg ingest`. Local-only: `dataset/` is git-ignored wholesale, so\n"
        "# every machine writes its own rather than the pointer travelling through git.\n"
        + yaml.safe_dump(
            {
                "path": str(adapted_root.resolve()),
                "train": f"train/{VISIBLE}/{IMAGES_SEGMENT}",
                "val": f"val/{VISIBLE}/{IMAGES_SEGMENT}",
                "rgbt": {"optical_token": VISIBLE, "thermal_token": INFRARED},
            },
            sort_keys=False,
        )
    )
    return destination


def already_populated(root: Path) -> bool:
    """True if ``root`` exists and holds anything.

    Mirrors the fetch script's idempotent-skip convention: a dataset already adapted should
    not have its (potentially 14 GB) image set walked again on every invocation.
    """
    return root.exists() and any(root.iterdir())
